# -*- coding: utf-8 -*-
"""Financial-Report-Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQ-Ni1_a6EsDs36NC5-6yWHs4fo49UCQ
"""

import pandas as pd

df = pd.read_excel("/content/Financial Sample.xlsx")

df.head()

import pandas as pd

df = pd.read_excel("/content/Financial Sample.xlsx")

print(df.columns)

import pandas as pd

df = pd.read_excel("/content/Financial Sample.xlsx")
df.columns = df.columns.str.strip()

# Core metrics
total_sales = df['Gross Sales'].sum()
total_profit = df['Profit'].sum()
profit_margin = (total_profit / total_sales) * 100

# Insights
top_country = df.groupby('Country')['Gross Sales'].sum().idxmax()
top_product = df.groupby('Product')['Profit'].sum().idxmax()

# Monthly trend
monthly_sales = df.groupby('Month Name')['Gross Sales'].sum()

print("Total Sales:", total_sales)
print("Profit Margin:", round(profit_margin, 2), "%")

# Remove extra spaces
df.columns = df.columns.str.strip()

print("Columns after cleaning:", df.columns)

# Use correct column names
total_sales = df['Gross Sales'].sum()
total_profit = df['Profit'].sum()

top_country = df.groupby('Country')['Gross Sales'].sum().idxmax()
top_product = df.groupby('Product')['Profit'].sum().idxmax()

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Top Country:", top_country)
print("Top Product:", top_product)

!pip install openai

api_key = "YOUR_API_KEY"

def generate_insights(total_sales, total_profit, top_country, top_product):

    summary = f"""
    Executive Summary:
    The company generated total sales of {total_sales} and profit of {total_profit}.
    The top performing country is {top_country}, and the most profitable product is {top_product}.
    """

    risks = """
    Key Risks:
    - High dependency on a single country for revenue
    - Profit margins may decrease if costs increase
    """

    opportunities = f"""
    Growth Opportunities:
    - Expand sales in regions similar to {top_country}
    - Increase production of {top_product}
    """

    return summary + risks + opportunities


# Call function
insights = generate_insights(total_sales, total_profit, top_country, top_product)

print(insights)

import matplotlib.pyplot as plt

# Monthly sales chart
monthly_sales.plot(kind='bar')

plt.title("Monthly Sales Performance")
plt.xlabel("Month")
plt.ylabel("Sales")

plt.xticks(rotation=45)
plt.show()

def generate_insights():

    return f"""
EXECUTIVE SUMMARY:
The company generated total sales of {total_sales:.2f} with a profit margin of {profit_margin:.2f}%.
The strongest market is {top_country}, and the most profitable product is {top_product}.

KEY RISKS:
- Increasing dependency on {top_country} may create regional risk.
- Profit margin needs monitoring due to cost fluctuations.

GROWTH OPPORTUNITIES:
- Expand high-performing product '{top_product}' into new regions.
- Improve low-performing months based on sales trends.

RECOMMENDATIONS:
- Optimize pricing strategy
- Reduce unnecessary discounts
- Focus on high-margin products
"""

insights = generate_insights()
print(insights)

!pip install reportlab

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

def create_pdf(text):
    doc = SimpleDocTemplate("Financial_Report.pdf")
    styles = getSampleStyleSheet()

    content = []

    # Title
    content.append(Paragraph("Financial Performance Report", styles['Title']))
    content.append(Spacer(1, 20))

    # Add content
    for line in text.split("\n"):
        content.append(Paragraph(line, styles["Normal"]))
        content.append(Spacer(1, 10))

    doc.build(content)

create_pdf(insights)

from google.colab import files
files.download("Financial_Report.pdf")

!pip install streamlit

